version: "3.0"

services:
  web:
    build: .
    image: project-dream-team-docker
    container_name: web
    networks:
      backend:
      frontend:
  db:
    image: mysql:5.7.17
    container_name: db
    networks:
      backend:
    volumes:
      - db-data:/var/lib/mysql
  nginx:
    build: ./nginx
    image: nginx
    container_name: nginx
    ports:
      - 80:80
    networks:
      backend:
      frontend:
networks:
  backend:
    internal: true
  frontend:
volumes:
  db-data:
secrets:
  example:
    external: true
