version: "3.1"

services:
  web:
    image: jagiles/project-dream-team-docker:latest
    container_name: web
    networks:
      backend:
      frontend:
  db:
    image: mysql:5.7.17
    container_name: db
    networks:
      backend:
    volumes:
      - db-data:/var/lib/mysql
networks:
  backend:
    internal: true
  frontend:
volumes:
  db-data:
